# Yocto: layers, build config, image, SDK, package feed, configure, flash. Included by the Makefile.

BRANCH := scarthgap
IMAGE  := btbench-image
YB     := $(YOCTO)/build-$(BOARD)
DEPLOY := $(YB)/tmp/deploy/images/$(MACHINE)

# MACHINE is exported as well as written into auto.conf: oe-init-build-env passes it through to
# bitbake, and auto.conf's hard assignment is what holds once the build is running.
BB = set -e && export MACHINE=$(MACHINE) && \
     . $(ROOT)/$(LAYERS)/poky/oe-init-build-env $(ROOT)/$(YB) >/dev/null &&
# The generated build config every bitbake invocation needs.
BUILD_CONF = $(YB)/conf/bblayers.conf auto-conf build-localconf $(SITE_LINK)

# What `make configure` writes. Neither is tracked by git.
#   DEVCONF  — baked into the image (hostname, root password, ssh key, Wi-Fi). Copied from the
#              tracked .sample on first use.
#   SITECONF — where this machine keeps its Yocto caches. bitbake parses conf/site.conf before
#              conf/local.conf, so a ?= here wins over the defaults in local.conf.sample.
DEVCONF  := $(YOCTO)/meta-btbench/conf/btbench-device.conf
SITECONF := $(YOCTO)/conf/site.conf
SITE_LINK = $(if $(wildcard $(SITECONF)),$(YB)/conf/site.conf)

DEF_HOSTNAME     := btbench
DEF_PASSWORD     := btbench
DEF_SSH_PUBKEY   := $(firstword $(wildcard $(HOME)/.ssh/id_ed25519.pub $(HOME)/.ssh/id_rsa.pub))
DEF_WIFI_SSID    :=
DEF_WIFI_PSK     :=
DEF_WIFI_COUNTRY := SK
DEF_AP_PSK       := btbench-setup
DEF_AUDIO_MODE   := pipewire
DEF_DL_DIR       := $(if $(wildcard $(HOME)/yocto/downloads),$(HOME)/yocto/downloads,$(ROOT)/$(YOCTO)/downloads)
DEF_SSTATE_DIR   := $(ROOT)/$(YOCTO)/sstate-cache

# SRC=local builds the image's BlueZ, PipeWire, WirePlumber and kernel from the dev trees in src/
# (externalsrc) instead of the revisions pinned in yocto/conf/versions.conf.
SRC ?=

## ─── image ───────────────────────────────────────────────────────────────────

# The newest image of this board (meta-raspberrypi's names carry ".rootfs").
newest_image = ls -t $(DEPLOY)/$(IMAGE)-$(MACHINE)*.wic.bz2 2>/dev/null | head -1

.PHONY: image
image: check-host check-devconf $(BUILD_CONF) ## Build the image (BOARD=, KERNEL=next|rpi, SRC=local)
	@$(BB) bitbake $(IMAGE)
	@echo ""
	@IMG=$$($(newest_image)); \
	if [ -n "$$IMG" ]; then \
	  echo -e "$(BOLD)$$(du -h $$(readlink -f $$IMG) | cut -f1)$(OFF)  $$IMG"; \
	  echo -e "  flash it:  $(BOLD)make flash BOARD=$(BOARD) DISK=<device>$(OFF)"; \
	fi

.PHONY: bitbake
bitbake: check-host check-devconf $(BUILD_CONF) ## Run bitbake with the layers set up (ARGS=..., or no ARGS for a shell)
ifeq ($(ARGS),)
	@echo "Layers configured for BOARD=$(BOARD) (MACHINE=$(MACHINE)). 'exit' to leave."
	@$(BB) $$SHELL
else
	@$(BB) bitbake $(ARGS)
endif

## ─── SDK ─────────────────────────────────────────────────────────────────────

# The standard SDK of the image: cross toolchain, meson/cmake/autotools wrappers and a sysroot with
# the -dev packages of everything in the image. The dev targets (make bluez, ...) compile with it,
# so they see exactly the libraries the board runs. It is regenerated by hand: the image manifest
# it was made from is kept next to it, and check-sdk says when the image has moved on.
newest_sdk = ls -t $(YB)/tmp/deploy/sdk/*-$(IMAGE)-*-toolchain-*.sh 2>/dev/null | head -1
image_manifest = ls -t $(DEPLOY)/$(IMAGE)-$(MACHINE)*.manifest 2>/dev/null | head -1

.PHONY: sdk
sdk: check-host check-devconf $(BUILD_CONF) ## Build the SDK and install it into sdk/$(BOARD)
	@$(BB) bitbake $(IMAGE) -c populate_sdk
	@set -e; SH=$$($(newest_sdk)); \
	[ -n "$$SH" ] || { echo "No SDK installer in $(YB)/tmp/deploy/sdk."; exit 1; }; \
	echo -e "$(BOLD)Installing$(OFF) $$(basename $$SH) $(DIM)→ $(SDK_DIR)$(OFF)"; \
	rm -rf $(SDK_DIR); \
	sh "$$SH" -y -d $(SDK_DIR) >/dev/null; \
	M=$$($(image_manifest)); [ -z "$$M" ] || cp "$$(readlink -f $$M)" $(SDK_DIR)/.image.manifest; \
	echo -e "SDK ready: $(DIM)$$(ls $(SDK_DIR)/$(SDK_ENV_GLOB))$(OFF)"

# Every dev target depends on this. No SDK is an error; an SDK older than the image is a warning
# (a library the board now has may be missing from the sysroot, or be of another version).
.PHONY: check-sdk
check-sdk:
	@if [ -z "$(SDK_ENV)" ]; then \
	  echo -e "$(BOLD)No SDK for BOARD=$(BOARD).$(OFF) The dev targets compile with the image's SDK."; \
	  echo -e "\n  $(BOLD)make sdk$(OFF)   builds it from the image and installs it into sdk/$(BOARD)\n"; \
	  exit 1; fi
	@M=$$($(image_manifest)); \
	if [ -n "$$M" ] && [ -f $(SDK_DIR)/.image.manifest ] && \
	   ! cmp -s "$$(readlink -f $$M)" $(SDK_DIR)/.image.manifest; then \
	  echo -e "$(BOLD)Note:$(OFF) the image was rebuilt with other packages since the SDK was made."; \
	  echo -e "      $(DIM)Run 'make sdk' if a build now misses a library or links an old one.$(OFF)"; \
	fi

## ─── package feed ────────────────────────────────────────────────────────────

# Install a recipe's packages on the running board without a reflash: bitbake builds them, this PC
# serves the ipk feed, and the board reaches it through an ssh reverse tunnel (127.0.0.1:8000 on the
# board is this PC), so it works over the gadget link and Wi-Fi alike. The image's opkg config
# already points there.
#   make pkg ARGS=iperf3
#   make pkg ARGS=bluez5 PKGS="bluez5 bluez5-noinst-tools"
FEED_PORT ?= 8000
PKGS      ?= $(ARGS)

.PHONY: pkg
pkg: check-host check-devconf $(BUILD_CONF) ## Build recipe(s) ARGS=... and opkg-install them on the board (PKGS= to pick packages)
	@[ -n "$(ARGS)" ] || { echo "Usage: make pkg ARGS=<recipe> [PKGS=\"<package> ...\"]"; exit 1; }
	@$(BB) bitbake $(ARGS) && bitbake package-index
	@set -e; feed=$(ROOT)/$(YB)/tmp/deploy/ipk; \
	python3 -m http.server -b 127.0.0.1 -d $$feed $(FEED_PORT) >/dev/null 2>&1 & srv=$$!; \
	trap "kill $$srv 2>/dev/null" EXIT; sleep 0.5; \
	ssh $(SSH_OPTS) -o ControlPath=none -R 8000:127.0.0.1:$(FEED_PORT) $(TARGET) \
	  "opkg update >/dev/null && opkg install --force-reinstall $(PKGS)"

## ─── configure ───────────────────────────────────────────────────────────────

# Everything here can equally well be done by editing the files by hand; this target just means
# you do not have to know which setting lives in which of them.
.PHONY: configure
configure: ## Set hostname, password, ssh key, Wi-Fi, audio mode and the Yocto cache dirs (interactive)
	@set -e; \
	[ -f bench.conf ] || cp bench.conf.sample bench.conf; \
	[ -f $(DEVCONF) ] || cp $(DEVCONF).sample $(DEVCONF); \
	get() { sed -n "s|^$$2 *?\?= *\"\(.*\)\"|\1|p" "$$1" 2>/dev/null | head -1; }; \
	ask() { \
	  printf "\n  $(BOLD)%s$(OFF)\n  $(DIM)default: %s$(OFF)\n" "$$1" "$${2:-<empty>}" >&2; \
	  read -e -i "$$3" -r -p "  > " ANS || ANS=""; \
	  [ -n "$$ANS" ] || ANS="$$2"; \
	  case "$$ANS" in '~'/*) ANS="$$HOME$${ANS#\~}";; esac; \
	  case "$$ANS" in *'"'*) echo -e "\n  A double quote cannot go in a bitbake value. Edit the file by hand." >&2; exit 1;; esac; \
	}; \
	setkey() { \
	  f="$$1"; export K="$$2" V="$$3"; \
	  awk 'BEGIN { k = ENVIRON["K"]; v = ENVIRON["V"]; hit = 0 } \
	       index($$0, k) == 1 && substr($$0, length(k) + 1) ~ /^[ \t]*\??=/ { \
	         print k " ?= \"" v "\""; hit = 1; next } \
	       { print } \
	       END { if (!hit) print k " ?= \"" v "\"" }' "$$f" > "$$f.new" && mv "$$f.new" "$$f"; \
	}; \
	echo -e "\n$(DIM)The line is pre-filled with the current value: edit it, or clear it and press$(OFF)"; \
	echo -e "$(DIM)Enter to restore the default shown above it.$(OFF)"; \
	echo -e "\n$(BOLD)Device$(OFF) $(DIM)— baked into the image.$(OFF)"; \
	ask "Hostname (the board answers on <hostname>.local)" "$(DEF_HOSTNAME)" "$$(get $(DEVCONF) BTBENCH_HOSTNAME)"; host="$$ANS"; \
	ask "Root password (stored in the clear in $(DEVCONF))" "$(DEF_PASSWORD)" "$$(get $(DEVCONF) BTBENCH_ROOT_PASSWORD)"; pass="$$ANS"; \
	ask "ssh public key to authorize for root (the deploy targets log in with it)" "$(DEF_SSH_PUBKEY)" "$$(get $(DEVCONF) BTBENCH_SSH_PUBKEY)"; key="$$ANS"; \
	echo -e "\n$(BOLD)Wi-Fi$(OFF) $(DIM)— a first network to join. Empty is fine: the board then starts its setup AP and you add one from its page.$(OFF)"; \
	ask "Wi-Fi SSID" "$(DEF_WIFI_SSID)" "$$(get $(DEVCONF) BTBENCH_WIFI_SSID)"; ssid="$$ANS"; \
	psk=""; [ -z "$$ssid" ] || { ask "Wi-Fi password" "$(DEF_WIFI_PSK)" "$$(get $(DEVCONF) BTBENCH_WIFI_PSK)"; psk="$$ANS"; }; \
	ask "Wi-Fi country (2-letter regulatory domain)" "$(DEF_WIFI_COUNTRY)" "$$(get $(DEVCONF) BTBENCH_WIFI_COUNTRY)"; country="$$ANS"; \
	ask "Setup AP password (the board's own AP when it has no network; 8+ chars)" "$(DEF_AP_PSK)" "$$(get $(DEVCONF) BTBENCH_AP_PSK)"; appsk="$$ANS"; \
	echo -e "\n$(BOLD)Audio$(OFF) $(DIM)— the stack at first boot; switch any time with 'bench audio <mode>'.$(OFF)"; \
	ask "Audio mode (pipewire/bluealsa/none)" "$(DEF_AUDIO_MODE)" "$$(get $(DEVCONF) BTBENCH_AUDIO_MODE)"; mode="$$ANS"; \
	echo -e "\n$(BOLD)Build host$(OFF) $(DIM)— caches. Point them at a shared tree and every project reuses one.$(OFF)"; \
	ask "Yocto download dir (DL_DIR)" "$(DEF_DL_DIR)" "$$(get $(SITECONF) DL_DIR)"; dl="$$ANS"; \
	ask "Yocto sstate cache (SSTATE_DIR)" "$(DEF_SSTATE_DIR)" "$$(get $(SITECONF) SSTATE_DIR)"; ss="$$ANS"; \
	setkey $(DEVCONF) BTBENCH_HOSTNAME      "$$host"; \
	setkey $(DEVCONF) BTBENCH_ROOT_PASSWORD "$$pass"; \
	setkey $(DEVCONF) BTBENCH_SSH_PUBKEY    "$$key"; \
	setkey $(DEVCONF) BTBENCH_WIFI_SSID     "$$ssid"; \
	setkey $(DEVCONF) BTBENCH_WIFI_PSK      "$$psk"; \
	setkey $(DEVCONF) BTBENCH_WIFI_COUNTRY  "$$country"; \
	setkey $(DEVCONF) BTBENCH_AP_PSK        "$$appsk"; \
	setkey $(DEVCONF) BTBENCH_AUDIO_MODE    "$$mode"; \
	mkdir -p $$(dirname $(SITECONF)) "$$dl" "$$ss"; \
	{ echo "# Written by 'make configure'. Per-machine, not tracked by git."; \
	  echo "# bitbake parses conf/site.conf before conf/local.conf, so these win over the"; \
	  echo "# defaults in yocto/conf/local.conf.sample."; \
	  echo ""; } > $(SITECONF); \
	setkey $(SITECONF) DL_DIR     "$$dl"; \
	setkey $(SITECONF) SSTATE_DIR "$$ss"; \
	echo -e "\n$(BOLD)Written$(OFF)"; \
	echo "  $(DEVCONF)"; \
	echo "      hostname=$$host  wifi=$${ssid:-<none, setup AP>}  audio=$$mode"; \
	echo "  $(SITECONF)"; \
	echo "      DL_DIR=$$dl"; \
	echo "      SSTATE_DIR=$$ss"; \
	echo -e "\nNext: $(BOLD)make image$(OFF)\n"

## ─── flash ───────────────────────────────────────────────────────────────────

# Lists the disks you could plausibly write to: every whole disk that is not the one this system
# is running from. Not filtered on the "removable" flag: a card in a built-in reader
# (/dev/mmcblk0) reports RM=0. (--exclude 7 drops loop devices.) Expects $$ROOTDISK.
candidates = lsblk -dno NAME,SIZE,TRAN,MODEL --exclude 7 \
	     | grep -v "^$$(basename $$ROOTDISK) " | sed 's|^|  /dev/|'
rootdisk = lsblk -no PKNAME "$$(findmnt -no SOURCE /)" 2>/dev/null | head -1

.PHONY: flash
flash: ## Write the image to an SD card (DISK=/dev/...)
	@IMG=$$($(newest_image)); \
	if [ -z "$$IMG" ]; then echo "No image. Run 'make image BOARD=$(BOARD)' first."; exit 1; fi; \
	ROOTDISK="/dev/$$($(rootdisk))"; \
	if [ -z "$(DISK)" ]; then \
	  echo -e "Usage: $(BOLD)make flash BOARD=$(BOARD) DISK=<device>$(OFF)   e.g. /dev/sdb, /dev/mmcblk0\n"; \
	  echo "Disks on this machine (the system disk $$ROOTDISK is not listed):"; \
	  $(candidates); exit 1; fi; \
	if [ ! -b "$(DISK)" ]; then echo "$(DISK) is not a block device."; exit 1; fi; \
	if [ "$$(lsblk -dno TYPE $(DISK) 2>/dev/null | tr -d ' ')" != "disk" ]; then \
	  PARENT=$$(lsblk -no PKNAME $(DISK) 2>/dev/null | head -1); \
	  echo "$(DISK) is a partition, not a whole disk.$${PARENT:+ Did you mean /dev/$$PARENT?}"; exit 1; fi; \
	if [ "$(DISK)" = "$$ROOTDISK" ]; then \
	  echo "REFUSING: $(DISK) is the disk this system is running from."; exit 1; fi; \
	if lsblk -lno MOUNTPOINT $(DISK) | grep -qE '^(/|/boot|/boot/.*|/usr|/var|/etc|/home)$$'; then \
	  echo "REFUSING: $(DISK) carries a mounted system directory:"; \
	  lsblk -lno NAME,MOUNTPOINT $(DISK) | grep -E ' /'; exit 1; fi; \
	echo -e "$(BOLD)About to ERASE $(DISK) — everything on it is lost:$(OFF)"; \
	lsblk -o NAME,SIZE,TRAN,RM,MODEL,MOUNTPOINT $(DISK); \
	if [ "$$(lsblk -dno RM $(DISK) | tr -d ' ')" != "1" ]; then \
	  echo -e "\n  $(BOLD)WARNING: this disk is not flagged removable.$(OFF) That is normal for a card in a"; \
	  echo    "  built-in reader (/dev/mmcblk0), but it is also what an internal drive looks like."; \
	  echo    "  Check the size and model above before you continue."; \
	fi; \
	echo -e "\n  image: $$IMG"; \
	read -p $$'\nType YES to write it: ' ans; [ "$$ans" = "YES" ] || { echo "Cancelled."; exit 1; }; \
	for p in $$(lsblk -lno NAME,MOUNTPOINT $(DISK) | awk '$$2 != "" {print "/dev/"$$1}'); do \
	  echo "unmounting $$p"; sudo umount "$$p" || exit 1; \
	done; \
	BMAP=$${IMG%.wic.bz2}.wic.bmap; \
	if command -v bmaptool >/dev/null && [ -e "$$BMAP" ]; then \
	  sudo bmaptool copy --bmap "$$BMAP" "$$IMG" $(DISK); \
	else \
	  bunzip2 -c "$$IMG" | sudo dd of=$(DISK) bs=4M conv=fsync status=progress; \
	fi; \
	sync; \
	echo -e "\n$(BOLD)Done.$(OFF) Plug the board's USB data port into this PC: http://10.55.0.1"

## ─── setup ───────────────────────────────────────────────────────────────────

HOST_PKGS := gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio \
             python3 python3-pexpect xz-utils debianutils iputils-ping python3-git \
             python3-jinja2 python3-subunit zstd liblz4-tool file locales libacl1 bmap-tools \
             rsync bear jq curl device-tree-compiler

.PHONY: host-deps
host-deps: ## Install the host packages Yocto and the dev targets need (Debian/Ubuntu)
	@missing=""; for p in $(HOST_PKGS); do dpkg -s $$p >/dev/null 2>&1 || missing="$$missing $$p"; done; \
	if [ -z "$$missing" ]; then echo "All host dependencies already installed."; \
	else echo -e "Installing:$$missing\n"; sudo apt-get install -y $$missing; fi

.PHONY: check-host
check-host:
	@missing=""; for p in $(HOST_PKGS); do dpkg -s $$p >/dev/null 2>&1 || missing="$$missing $$p"; done; \
	if [ -n "$$missing" ]; then \
	  echo -e "Missing host packages:$$missing\nInstall them with:  $(BOLD)make host-deps$(OFF)"; exit 1; fi

# The layer `require`s DEVCONF, so a fresh clone would otherwise fail deep inside a bitbake parse.
.PHONY: check-devconf
check-devconf:
	@if [ ! -f $(DEVCONF) ]; then \
	  echo -e "$(BOLD)No device config.$(OFF) $(DEVCONF) is not tracked by git: it holds"; \
	  echo    "the root password and Wi-Fi PSK in the clear."; \
	  echo -e "\n  $(BOLD)make configure$(OFF)   set hostname, password, ssh key and Wi-Fi"; \
	  echo    "  or copy $$(basename $(DEVCONF)).sample over it and edit by hand"; \
	  exit 1; fi

# ─── generated build config ──────────────────────────────────────────────────

$(LAYERS)/poky:
	@echo "Cloning poky ($(BRANCH))..."
	@git clone -q --depth 1 -b $(BRANCH) https://git.yoctoproject.org/poky $@

$(LAYERS)/meta-openembedded:
	@echo "Cloning meta-openembedded ($(BRANCH))..."
	@git clone -q --depth 1 -b $(BRANCH) https://git.openembedded.org/meta-openembedded $@

$(LAYERS)/meta-raspberrypi:
	@echo "Cloning meta-raspberrypi ($(BRANCH))..."
	@git clone -q --depth 1 -b $(BRANCH) https://git.yoctoproject.org/meta-raspberrypi $@

$(YB)/conf/bblayers.conf: $(LAYERS)/poky $(LAYERS)/meta-openembedded $(BSP_LAYERS) \
                          $(YOCTO)/conf/bblayers.conf.sample $(BOARD_MK)
	@mkdir -p $(YB)/conf
	@printf '  %s \\\n' \
	  $(ROOT)/$(LAYERS)/poky/meta \
	  $(ROOT)/$(LAYERS)/poky/meta-poky \
	  $(ROOT)/$(LAYERS)/meta-openembedded/meta-oe \
	  $(ROOT)/$(LAYERS)/meta-openembedded/meta-python \
	  $(ROOT)/$(LAYERS)/meta-openembedded/meta-networking \
	  $(ROOT)/$(LAYERS)/meta-openembedded/meta-multimedia \
	  $(addprefix $(ROOT)/,$(BSP_LAYERS)) \
	  $(ROOT)/$(YOCTO)/meta-btbench > $(YB)/conf/.layers
	@sed -e '/@LAYERS@/{r $(YB)/conf/.layers' -e 'd}' \
	     $(YOCTO)/conf/bblayers.conf.sample > $(YB)/conf/bblayers.conf
	@rm -f $(YB)/conf/.layers
	@echo "Layers for BOARD=$(BOARD) written to $(YB)/conf/bblayers.conf."

# What makes this build dir this board's, this kernel's and (SRC=local) these sources'. Rewritten
# on every run but only replaced when it changed, so bitbake does not reparse for nothing.
# The board conf and versions.conf are required by absolute path rather than copied, so an edit to
# either is picked up (and tracked by bitbake) without regenerating anything here.
.PHONY: auto-conf
auto-conf: $(YB)/conf/bblayers.conf
	@{ echo "# Written by the Makefile for BOARD=$(BOARD) KERNEL=$(KERNEL)$(if $(SRC), SRC=$(SRC)). Do not edit:"; \
	   echo "# it is regenerated. One-off settings go in local.conf."; \
	   echo 'MACHINE = "$(MACHINE)"'; \
	   echo 'BTBENCH_BOARD = "$(BOARD)"'; \
	   echo 'BTBENCH_KERNEL = "$(KERNEL)"'; \
	   echo 'BTBENCH_KARCH = "$(KARCH)"'; \
	   echo 'BTBENCH_KIMAGE = "$(KIMAGE)"'; \
	   echo 'BTBENCH_KDEFCONFIG = "$(DEFCONFIG_$(KERNEL))"'; \
	   echo 'BTBENCH_DTBS = "$(DTBS_$(KERNEL))"'; \
	   echo 'BTBENCH_DTS_EXTRA = "$(if $(DTS_EXTRA_$(KERNEL)),$(ROOT)/$(DTS_EXTRA_$(KERNEL)))"'; \
	   echo 'BTBENCH_TRY_METHOD = "$(TRY_METHOD)"'; \
	   echo 'BTBENCH_GADGET_UDC = "$(GADGET_UDC)"'; \
	   echo 'BTBENCH_BT_HCI = "$(BT_HCI)"'; \
	   echo 'BTBENCH_ROOT = "$(ROOT)"'; \
	   echo 'require $(ROOT)/$(YOCTO)/conf/versions.conf'; \
	   echo 'require $(ROOT)/$(BOARD_CONF)'; \
	   if [ "$(SRC)" = "local" ]; then \
	     echo ''; \
	     echo '# SRC=local: the image is built from the dev trees.'; \
	     echo 'INHERIT += "externalsrc"'; \
	     echo 'EXTERNALSRC:pn-bluez5 = "$(BLUEZ_SRC)"'; \
	     echo 'EXTERNALSRC_BUILD:pn-bluez5 = "$${WORKDIR}/build"'; \
	     echo 'EXTERNALSRC:pn-pipewire = "$(PIPEWIRE_SRC)"'; \
	     echo 'EXTERNALSRC_BUILD:pn-pipewire = "$${WORKDIR}/build"'; \
	     echo 'EXTERNALSRC:pn-wireplumber = "$(WIREPLUMBER_SRC)"'; \
	     echo 'EXTERNALSRC_BUILD:pn-wireplumber = "$${WORKDIR}/build"'; \
	     if [ "$(KERNEL)" = "next" ]; then \
	       echo 'EXTERNALSRC:pn-linux-btbench = "$(LINUX_SRC)"'; \
	       echo 'EXTERNALSRC_BUILD:pn-linux-btbench = "$${WORKDIR}/build"'; \
	     fi; \
	   fi; } > $(YB)/conf/auto.conf.new
	@if [ "$(SRC)" = "local" ]; then \
	  for d in $(BLUEZ_SRC) $(PIPEWIRE_SRC) $(WIREPLUMBER_SRC) $(if $(filter next,$(KERNEL)),$(LINUX_SRC)); do \
	    [ -d $$d ] || { echo -e "$(BOLD)SRC=local:$(OFF) $$d does not exist. Run $(BOLD)make src$(OFF) first."; \
	                    rm -f $(YB)/conf/auto.conf.new; exit 1; }; done; fi
	@cmp -s $(YB)/conf/auto.conf.new $(YB)/conf/auto.conf && rm -f $(YB)/conf/auto.conf.new \
	  || mv $(YB)/conf/auto.conf.new $(YB)/conf/auto.conf

# local.conf is yours to edit, so it is only ever created, never rewritten.
.PHONY: build-localconf
build-localconf: $(YB)/conf/bblayers.conf
	@if [ ! -f $(YB)/conf/local.conf ]; then \
	  cp $(YOCTO)/conf/local.conf.sample $(YB)/conf/local.conf; \
	  echo "Build config written to $(YB)/conf/ (local.conf is yours to edit)."; \
	fi

# Copied rather than symlinked so that removing the build dir cannot take the original with it.
$(YB)/conf/site.conf: $(SITECONF) $(YB)/conf/bblayers.conf
	@cp $(SITECONF) $@
